/* Generated file: node data-scripts/find-all-components.js */

import PrimaryNav from './components/PrimaryNav.vue'
import SidebarNav from './components/SidebarNav.vue'
import Orbit from './components/space/Orbit.vue'
import StoryTeller from './components/toys/StoryTeller.vue'
import ColumnLayout from './components/ui/ColumnLayout.vue'
import GridFill from './components/ui/GridFill.vue'
import HighlightedQuadrantInfo from './components/ui/HighlightedQuadrantInfo.vue'
import HorizontalTileGrid from './components/ui/HorizontalTileGrid.vue'
import Icon from './components/ui/Icon.vue'
import IconButton from './components/ui/IconButton.vue'
import PanAndZoom from './components/ui/PanAndZoom.vue'
import Property from './components/ui/Property.vue'
import PropertyPanel from './components/ui/PropertyPanel.vue'
import QuadrantBreakdown from './components/ui/QuadrantBreakdown.vue'
import Tabulation from './components/ui/Tabulation.vue'
import VerticalTileGrid from './components/ui/VerticalTileGrid.vue'
import ContactManagement from './views/ContactManagement.vue'
import Designer from './views/Designer.vue'
import EstablishContact from './views/EstablishContact.vue'
import Diplomacy from './views/galaxy/Diplomacy.vue'
import Fleets from './views/galaxy/Fleets.vue'
import GalaxyView from './views/galaxy/GalaxyView.vue'
import History from './views/galaxy/History.vue'
import Intelligence from './views/galaxy/Intelligence.vue'
import KnownLifeforms from './views/galaxy/KnownLifeforms.vue'
import Outposts from './views/galaxy/Outposts.vue'
import Planets from './views/galaxy/Planets.vue'
import Research from './views/galaxy/Research.vue'
import Statistics from './views/galaxy/Statistics.vue'
import Threats from './views/galaxy/Threats.vue'
import Trade from './views/galaxy/Trade.vue'
import GalaxyInputs from './views/galaxy/ui/GalaxyInputs.vue'
import GalaxyNav from './views/galaxy/ui/GalaxyNav.vue'
import GalaxySVG from './views/galaxy/ui/GalaxySVG.vue'
import Home from './views/Home.vue'
import LocationView from './views/LocationView.vue'
import Omniscience from './views/omniscience/Omniscience.vue'
import Regions from './views/omniscience/Regions.vue'
import SolarSystem from './views/omniscience/SolarSystem.vue'
import StellarArchetypes from './views/omniscience/StellarArchetypes.vue'
import Systems from './views/omniscience/Systems.vue'
import OmniscienceNav from './views/omniscience/ui/OmniscienceNav.vue'
import RegionTypes from './views/omniscience/ui/RegionTypes.vue'
import ComponentTests from './views/settings/debug/ComponentTests.vue'
import Debug from './views/settings/debug/Debug.vue'
import Gamedata from './views/settings/Gamedata.vue'
import Mods from './views/settings/Mods.vue'
import Settings from './views/settings/Settings.vue'
import SettingsNav from './views/settings/ui/SettingsNav.vue'
import SystemView from './views/SystemView.vue'
import Template from './views/Template.vue'
import Universe from './views/Universe.vue'

export default {
  PrimaryNav, SidebarNav, Orbit, StoryTeller, ColumnLayout, GridFill, HighlightedQuadrantInfo, HorizontalTileGrid, Icon, IconButton, PanAndZoom, Property, PropertyPanel, QuadrantBreakdown, Tabulation, VerticalTileGrid, ContactManagement, Designer, EstablishContact, Diplomacy, Fleets, GalaxyView, History, Intelligence, KnownLifeforms, Outposts, Planets, Research, Statistics, Threats, Trade, GalaxyInputs, GalaxyNav, GalaxySVG, Home, LocationView, Omniscience, Regions, SolarSystem, StellarArchetypes, Systems, OmniscienceNav, RegionTypes, ComponentTests, Debug, Gamedata, Mods, Settings, SettingsNav, SystemView, Template, Universe
}